Ma30 609
mscripts-adherence/rules-runner-fn pull request #3
Opened 2022-03-22 03:05 UTC by cah-venkatesh-manchala

2022-03-22 06:31 UTC, cah-rainy-jain commented on tests/http-input/http-input.test.js
> +  let payload = {
Please update the tests wrt the schema

2022-03-22 17:30 UTC, cah-josef-salyer requested changes
Is there any way to break these changes up?  It seems like every file changed for just the http-input....

2022-03-22 19:28 UTC, cah-venkatesh-manchala commented on test-report/index.html
> +<html><head><meta charset="utf-8"/><title>Program Management</title><style type="text/css">html,
I will add this file to .gitignore file

2022-03-22 19:29 UTC, cah-venkatesh-manchala commented on tests/load-patient-state/load-patient-state.test.js
> +  it("should return 200 from post route", async () => {
Except http-input, all of the test classes are just present. so I just left it. The people who work in load-patient will rewrite these test cases.

2022-03-23 09:50 UTC, cah-rainy-jain commented on index.js
> +const schemaPath = `./src/${process.env.FN}/request.schema.json`;
I dont think we are using request.schema.json

2022-03-23 18:27 UTC, JHock974 approved these changes

2022-03-25 12:18 UTC, cah-josef-salyer approved these changes

2022-03-27 23:56 UTC, merged